{"errorMessage": "(1205, 'Lock wait timeout exceeded; try restarting transaction')", "errorType": "OperationalError", "stackTrace": ["  File \"/var/task/tennisclient.py\", line 52, in handler\n    cur.execute('delete from players')\n", "  File \"/var/task/pymysql/cursors.py\", line 163, in execute\n    result = self._query(query)\n", "  File \"/var/task/pymysql/cursors.py\", line 321, in _query\n    conn.query(q)\n", "  File \"/var/task/pymysql/connections.py\", line 505, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n", "  File \"/var/task/pymysql/connections.py\", line 724, in _read_query_result\n    result.read()\n", "  File \"/var/task/pymysql/connections.py\", line 1069, in read\n    first_packet = self.connection._read_packet()\n", "  File \"/var/task/pymysql/connections.py\", line 676, in _read_packet\n    packet.raise_for_error()\n", "  File \"/var/task/pymysql/protocol.py\", line 223, in raise_for_error\n    err.raise_mysql_exception(self._data)\n", "  File \"/var/task/pymysql/err.py\", line 107, in raise_mysql_exception\n    raise errorclass(errno, errval)\n"]}